### ISSUE TITLE
plugin has been stoped working

### ISSUE THREAD

**Issue by arashtotti88** [nRafinia/Emby.Subtitle.Subf2m#1]
Hello boss

plugin has been stopped working for emby beta version 4.7.0.30

is there any chance to see a fixed update for this great plugin?

thanks a lot

**Comment by nRafinia** [comment]
Hello
I check and fix the problem

**Comment by arashtotti88** [comment]
the best news ever

thanks again for a great job

**Comment by nRafinia** [comment]
I checked and did not see any problem, can you send me the log file?

**Comment by arashtotti88** [comment]
https://www.dropbox.com/s/h3byg47hpkc5i3u/emby%20log.zip?dl=0

**Comment by nRafinia** [comment]
Please check the latest version
https://github.com/nRafinia/Emby.Subtitle.Subf2m/releases/latest

**Comment by arashtotti88** [comment]
I still can't see any results when I search subtitles ( only opensubtitles appear )

**Comment by arashtotti88** [comment]
after updating to the latest version
https://www.dropbox.com/s/o2u2fvnqpybtvkl/logs.zip?dl=0

**Comment by nRafinia** [comment]
Please redownload latest version and recheck

**Comment by arashtotti88** [comment]
still no result after re-download and restart emby server

https://www.dropbox.com/s/lst0wv4zh48xlt1/logs%28%20after%20redownload%20%29.zip?dl=0

**Comment by nRafinia** [comment]
Please install this version 
https://github.com/nRafinia/Emby.Subtitle.Subf2m/releases/tag/1.0.1

**Comment by arashtotti88** [comment]
still doesn't work 
https://www.dropbox.com/s/2p2zish1h7qh8ny/logs%20%28%20Emby.Subtitle.SubF2M%20%29.zip?dl=0


------

is that plugin work for yourself ? if yes which version of emby do you use. 

thanks

**Comment by nRafinia** [comment]
My version is 4.6.7.0

new release: https://github.com/nRafinia/Emby.Subtitle.Subf2m/releases/tag/1.1.1

**Comment by nRafinia** [comment]
https://github.com/nRafinia/Emby.Subtitle.Subf2m/releases/tag/1.2.1

**Comment by arashtotti88** [comment]
doesn't work

logs 1.2 version.zip
https://www.dropbox.com/s/nn3z3x2ej0a9eno/logs%201.2%20version.zip?dl=0


logs 1.2.1 version.zip
https://www.dropbox.com/s/cp79z8exui9t9f7/logs%201.2.1%20version.zip?dl=0

**Comment by arashtotti88** [comment]
plugin work like charm with stable version of emby

https://www.dropbox.com/s/edb1435m7lb8rqc/logs%204.6.7.0%20%20version.zip?dl=0

[https://imgur.com/a/um1L7bL](url)

**Comment by arashtotti88** [comment]
I'm going to uninstall the stable version and reinstall the beta version and check again the plugin and see the results...

**Comment by arashtotti88** [comment]
definitely, the plugin has a problem with the beta version of emby...

after reinstalling the beta version of emby and installing the plugin, still, I don't see any subtitles for any movies ...

**Comment by nRafinia** [comment]
Hi
Please download latest version
