### ISSUE TITLE
Plugin hangs at exactly the same point in scan

### ISSUE THREAD

**Issue by Akirainblack** [nRafinia/Emby.Subtitle.Subf2m#2]
First off, thank you so much for this plugin.
I'm updating my subs, however it keeps getting to EXACTLY 60.4% through my film library and then it "hangs".
If I tell it to stop the scheduled task it then hangs "stopping" the task.
I have to reboot the emby server to get it working again.
I'm running the latest stable emby in docker with the latest release of this plugin.

Please advise how I can find the culprit film or resolve this?

Thank you,

**Comment by nRafinia** [comment]
Hi
Can send me your log file?
