### ISSUE TITLE
No result in latest release 1.1.4

### ISSUE THREAD

**Issue by Fahad-Beta** [nRafinia/Emby.Subtitle.Subf2m#3]
Hello ,

Thank you for this amazing plugin but just to let you know it's not working with the latest empy update 4.7.0.60

I have updated the plugin to the lates version 1.1.4.0
also tried the old one 1.2.0 but no luck still subtitles are not showing.

**Comment by Fahad-Beta** [comment]
@nRafinia hope you are doing well
 any update or plan to fix this

**Comment by nRafinia** [comment]
Can send me your log file?

**Comment by Fahad-Beta** [comment]
> 

@nRafinia Attached. I did try multiple versions of Subf2m so this is most likely a compatiblety issue with latest Emby release s

[embyserver.txt](https://github.com/nRafinia/Emby.Subtitle.Subf2m/files/8833333/embyserver.txt)

**Comment by nRafinia** [comment]
Hi
Problem is fixed, Please download latest version.
https://github.com/nRafinia/Emby.Subtitle.Subf2m/releases/latest

**Comment by Fahad-Beta** [comment]
> Hi
> Problem is fixed, Please download latest version.
> https://github.com/nRafinia/Emby.Subtitle.Subf2m/releases/latest

Confirmed, everything is OK in the latest release thank you for your support
